.TH YASUNA "6" "2015年2月" "ユーザコマンド"
.SH 名前
yasuna \- 折部やすなの名言を表示する
.SH 書式
.B yasuna
[\fIオプション\fR]...
.br
.B yasuna
\fI--dict=PATH\fR [\fIオプション\fR]...
.SH 説明
.PP
キルミーベイベーの登場人物である、折部やすなの名言をランダムで標準出力へ表示します。
.br
単語ファイルが\fB\-\-dict=PATH\fRオプションにて指定されていない限り、
.br
標準でPREFIX/share/yasuna/yasuna-quotesが使用されます。
長いオプションに必須の引数は短いオプションにも必須です。
.TP
\fB\-l\fR, \fB\-\-list\fR
\&単語のリストを番号付きで表示し終了する
.TP
\fB\-n\fR, \fB\-\-number=INT\fR
\&\fB\-\-list\fR で得た番号(INT)を指定して表示する
.TP
\fB\-f\fR, \fB-\-file\fR
\&使用する単語ファイル(PATH)を指定する
.TP
\fB\-h\fR, \fB-\-help\fR
\&この使い方を表示して終了する
.TP
\fB\-v\fR, \fB\-\-version\fR
\&バージョン情報を表示して終了する

.SS "終了ステータス:"
.TP
0
正常終了、
.TP
1
単語ファイルのパスを格納する為のメモリ領域の確保（malloc）に失敗、
.TP
2
単語ファイルが存在しない、
.TP
3
単語ファイルのパスがディレクトリだった、
.TP
4
単語ファイルに対するアクセス権限が無い、
.TP
5
指定されたファイルがプレーンテキストでは無い、
.TP
6
ファイルのオープンに失敗した、
.TP
7
単語の文字列長が、BUFLENとして定義されているバッファ容量を超えている、　
.TP
255
引数の解析に失敗（例：無効な引数を渡した）
.PP
標準で使用する単語ファイルはMakefileの\fIDICDIR変数\fR及び、\fIDICNME変数\fRで変更できます。
一時的なバッファの最大サイズは、必要に応じてyasuna.hの\fIBUFLEN定数\fRにて変更して下さい。
.SH 謝辞
元々このプログラムの発端は、@844196さんのRengeです。
.br
更にはHomebrew用のリポジトリまで提供して頂きました。本当にありがとうございます。
.SH 作者
sasairc (@sasairc)
.SH 著作権
Copyright(c) 2015 sasairc <sasairc@ssiserver.moe.hm>
.br
This work is free. You can redistribute it and/or modify it under the
.br
terms of the Do What The Fuck You Want To Public License, Version 2,
.br
as published by Sam Hocevar.HocevarHocevar See the COPYING file or http://www.wtfpl.net/
.br
for more details.

.SH 関連項目
.B renge
.B cowsay
