.TH YASUNA "6" "2015年2月" "ユーザコマンド"
.SH 名前
yasuna \- 折部やすなの名言を表示する
.SH 書式
.B yasuna
[\fIオプション\fR]...
.br
.B yasuna
\fI--file=PATH\fR [\fIオプション\fR]...
.SH 説明
.PP
キルミーベイベーの登場人物である、折部やすなちゃんの名言をランダムで標準出力へ出力します。
.br
単語ファイルが\fI\-\-file=PATH\fRオプションにて指定されていない限り、標準でPREFIX/share/yasuna/yasuna-quotesが使用されます。
.br
長いオプションに必須の引数は短いオプションにも必須です。
.TP
\fB\-l\fR, \fB\-\-list\fR
\&単語のリストを番号付きで表示し終了する
.TP
\fB\-n\fR, \fB\-\-number\fR\fI=INT\fR
\&\fB\-\-list\fR で得た番号(INT)を指定して表示する
.TP
\fB\-f\fR, \fB-\-file\fR\fI=FILE\fR
\&使用する単語ファイル(PATH)を指定する
.TP
\fB\-h\fR, \fB-\-help\fR
\&この使い方を表示して終了する
.TP
\fB\-v\fR, \fB\-\-version\fR
\&バージョン情報を表示して終了する

.SS "終了ステータス:"
.TP
0
正常終了、
.TP
1
ファイルパスの連結に失敗した、
.TP
2
指定された単語ファイルが存在しないか、通常ファイルではなくディレクトリである
または通常ファイルに対するアクセス権が無い、
.TP
3
指定された通常ファイルは存在するが、プレーンテキストでは無い
または、ファイルのオープンに失敗した、
.TP
4
メモリの確保に失敗した、
.TP
255
引数の解析に失敗（例：無効な引数を渡した）
.SH "追加情報"
.PP
標準で使用する単語ファイルは、Makefileの\fIDICDIR変数\fR及び、\fIDICNME変数\fRにて指定されます。
.PP
単語ファイルより読み込んだデータを格納するバッファの容量初期値及び、再確保する際に加算される値は、
.br
src/config.hの\fITH_LINES\fR定数と\fITH_LENGTH\fR定数にて変更できます。
.SH 謝辞
元々このプログラムの発端は、@844196さんのRengeです。
.br
更にはHomebrew用のリポジトリまで提供して頂きました。本当にありがとうございます。
.SH 作者
sasairc (@sasairc)
.SH 著作権
Copyright(c) 2015 sasairc <sasairc@ssiserver.moe.hm>
.br
This work is free. You can redistribute it and/or modify it under the
.br
terms of the Do What The Fuck You Want To Public License, Version 2,
.br
as published by Sam Hocevar.HocevarHocevar See the COPYING file or http://www.wtfpl.net/
.br
for more details.

.SH 関連項目
.B renge
.B clangsay
.B cowsay
