#
#    Makefile for yasuna
#

install-doc: LICENSE cli_spec.md dictionary_spec.md
	install -pd $(DOCDIR)/polyaness
	install -pm 644 LICENSE $(DOCDIR)/polyaness
	install -pm 644 *.md $(DOCDIR)/polyaness
